#!/usr/bin/env python3
"""
tokenize_er.py — Tokenize ER extraction training data for ANE fine-tuning.

Reads:  er_training_data.jsonl  (generated by generate.py)
Writes: er_train.bin            (binary, packed (input, output) token pairs)

Binary format:
  Header:  [magic: u32 = 0x45525F31][n_examples: u32]
  Records: [input_len: u16][total_len: u16][tokens: u16 × total_len] ...

- input_len  = number of instruction+text tokens
- total_len  = input_len + output_len (entity/relation lines)
- tokens     = full sequence: input tokens followed immediately by output tokens
- Loss is computed only on positions [input_len-1 .. total_len-2]
  (predict output tokens from output positions)

Usage:
    uv run python3 tokenize_er.py
    uv run python3 tokenize_er.py --input er_training_data.jsonl --output er_train.bin
    uv run python3 tokenize_er.py --max-seq 512 --stats
"""

import argparse
import json
import struct
import sys
from pathlib import Path
from collections import Counter

# Max sequence length must match SEQ in er_config.h
DEFAULT_MAX_SEQ = 512
MAGIC = 0x45525F31  # "ER_1"

# ── Tokenizer ────────────────────────────────────────────────────────────────

def load_tokenizer():
    """Load LLaMA tokenizer (SentencePiece, 32K vocab). Downloads on first use."""
    try:
        from transformers import LlamaTokenizer
    except ImportError:
        print("ERROR: transformers not installed. Run: uv sync", file=sys.stderr)
        sys.exit(1)

    # huggyllama/llama-7b is a public community mirror — only tokenizer files
    # are downloaded (~500KB), not model weights
    model_id = "huggyllama/llama-7b"
    print(f"Loading tokenizer from {model_id} (downloads ~500KB on first use)...")
    try:
        tok = LlamaTokenizer.from_pretrained(model_id, legacy=False)
    except Exception as e:
        print(f"ERROR loading tokenizer: {e}", file=sys.stderr)
        print("If offline, copy tokenizer.model to ./tokenizer.model and re-run", file=sys.stderr)
        sys.exit(1)

    print(f"Tokenizer loaded. Vocab size: {tok.vocab_size}")
    assert tok.vocab_size == 32000, f"Expected vocab=32000, got {tok.vocab_size}"
    return tok


def tokenize_pair(tok, input_text: str, output_text: str) -> tuple[list[int], list[int]]:
    """
    Tokenize an (input, output) pair.

    The input gets BOS prepended.
    The output gets EOS appended.
    Returns (input_ids, output_ids).
    """
    # BOS + input text (no EOS — model predicts first output token at the boundary)
    input_ids = tok.encode(input_text, add_special_tokens=True)  # adds BOS

    # Output text + EOS
    # encode without special tokens then manually add EOS, so BOS isn't duplicated
    output_ids = tok.encode(output_text, add_special_tokens=False)
    output_ids.append(tok.eos_token_id)

    return input_ids, output_ids


# ── Binary I/O ────────────────────────────────────────────────────────────────

def write_dataset(records: list[tuple[list[int], list[int]]], path: Path):
    """Write packed binary file."""
    with open(path, "wb") as f:
        # Header
        f.write(struct.pack("<II", MAGIC, len(records)))
        for input_ids, output_ids in records:
            total = len(input_ids) + len(output_ids)
            tokens = input_ids + output_ids
            f.write(struct.pack("<HH", len(input_ids), total))
            f.write(struct.pack(f"<{total}H", *tokens))
    print(f"Wrote {len(records)} records to {path} ({path.stat().st_size / 1e6:.2f} MB)")


def read_dataset(path: Path) -> list[tuple[list[int], list[int]]]:
    """Read binary file back (for verification)."""
    records = []
    with open(path, "rb") as f:
        magic, n = struct.unpack("<II", f.read(8))
        assert magic == MAGIC, f"Bad magic: {magic:#x}"
        for _ in range(n):
            input_len, total_len = struct.unpack("<HH", f.read(4))
            tokens = list(struct.unpack(f"<{total_len}H", f.read(total_len * 2)))
            records.append((tokens[:input_len], tokens[input_len:]))
    return records


# ── Stats ─────────────────────────────────────────────────────────────────────

def print_stats(records: list[tuple[list[int], list[int]]], max_seq: int):
    input_lens  = [len(i) for i, _ in records]
    output_lens = [len(o) for _, o in records]
    total_lens  = [i + o for i, o in zip(input_lens, output_lens)]

    n = len(records)
    print(f"\n{'='*50}")
    print(f"Dataset statistics ({n} examples)")
    print(f"{'='*50}")
    for label, vals in [("input_len", input_lens), ("output_len", output_lens), ("total_len", total_lens)]:
        print(f"  {label:12s}  min={min(vals):4d}  median={sorted(vals)[n//2]:4d}  "
              f"max={max(vals):4d}  mean={sum(vals)/n:5.1f}")

    over = sum(1 for t in total_lens if t > max_seq)
    print(f"  Truncated/skipped (> {max_seq} tokens): {over} ({100*over/n:.1f}%)")
    print(f"  Total tokens: {sum(total_lens):,}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Tokenize ER extraction data for ANE training")
    parser.add_argument("--input",   default="er_training_data.jsonl")
    parser.add_argument("--output",  default="er_train.bin")
    parser.add_argument("--max-seq", type=int, default=DEFAULT_MAX_SEQ,
                        help=f"Max sequence length (default: {DEFAULT_MAX_SEQ}, must match er_config.h SEQ)")
    parser.add_argument("--stats",   action="store_true", help="Print detailed stats")
    parser.add_argument("--verify",  action="store_true", help="Round-trip verify after writing")
    args = parser.parse_args()

    input_path  = Path(__file__).parent / args.input
    output_path = Path(__file__).parent / args.output

    if not input_path.exists():
        print(f"ERROR: {input_path} not found. Run generate.py first.", file=sys.stderr)
        sys.exit(1)

    # Count lines
    with open(input_path) as f:
        n_lines = sum(1 for _ in f)
    print(f"Input: {input_path} ({n_lines} examples)")

    tok = load_tokenizer()

    records = []
    skipped_too_long = 0
    skipped_bad      = 0
    domain_counts: Counter = Counter()

    from tqdm import tqdm
    with open(input_path) as f:
        for line in tqdm(f, total=n_lines, desc="Tokenizing"):
            try:
                ex = json.loads(line)
            except json.JSONDecodeError:
                skipped_bad += 1
                continue

            input_text  = ex.get("input",  "")
            output_text = ex.get("output", "")
            domain      = ex.get("domain", "unknown")

            if not input_text or not output_text:
                skipped_bad += 1
                continue

            input_ids, output_ids = tokenize_pair(tok, input_text, output_text)
            total = len(input_ids) + len(output_ids)

            if total > args.max_seq:
                # Try truncating input side (keep output intact)
                max_input = args.max_seq - len(output_ids)
                if max_input < 10:
                    skipped_too_long += 1
                    continue
                input_ids = input_ids[:max_input]
                total = len(input_ids) + len(output_ids)

            # Must have at least 1 output token for loss
            if len(output_ids) < 1:
                skipped_bad += 1
                continue

            records.append((input_ids, output_ids))
            domain_counts[domain] += 1

    print(f"\nSkipped: {skipped_too_long} too long, {skipped_bad} malformed")
    print(f"Kept: {len(records)} examples")

    print("\nExamples per domain:")
    for domain, count in sorted(domain_counts.items()):
        print(f"  {domain:35s} {count:4d}")

    if not records:
        print("ERROR: No valid records. Check input file.", file=sys.stderr)
        sys.exit(1)

    write_dataset(records, output_path)

    if args.stats or True:  # always print stats
        print_stats(records, args.max_seq)

    if args.verify:
        print("\nVerifying round-trip...")
        loaded = read_dataset(output_path)
        assert len(loaded) == len(records)
        for i, ((ii, oi), (il, ol)) in enumerate(zip(records, loaded)):
            assert ii == il and oi == ol, f"Mismatch at record {i}"
        print("Verification passed.")


if __name__ == "__main__":
    main()
